"use client";

import Navbar from "@/app/components/landing/Navbar";
import Footer from "@/app/components/landing/Footer";
import { useRouter } from "next/navigation";

export default function TermsPage() {
  const router = useRouter();
  return (
    <main className="bg-white min-h-screen" style={{ fontFamily: "var(--font-sans)" }}>
      <Navbar />

      <section className="bg-[#FDFAF5] px-6 pb-20 pt-32 md:px-12 md:pb-28 md:pt-44 lg:pt-52 lg:px-20">
        <div className="max-w-6xl mx-auto">
          <div className="mx-auto max-w-4xl">
            <div className="flex items-center mb-14 md:mb-16">
              <button onClick={() => router.back()} className="inline-flex items-center gap-2 text-xs tracking-[0.2em] transition-colors cursor-pointer shrink-0" style={{ fontFamily: "var(--font-sans)", color: "#5A554E" }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <line x1="19" y1="12" x2="5" y2="12" />
                  <polyline points="12 19 5 12 12 5" />
                </svg>
                BACK
              </button>
              <div className="flex-1 flex justify-center">
                <h1 className="text-[#2C2A26] text-[22px] md:text-[26px] lg:text-[28px] font-light tracking-[0.08em]" style={{ fontFamily: "var(--font-serif)" }}>Terms &amp; Conditions</h1>
              </div>
              <div className="shrink-0 w-[43px]" />
            </div>

          <div className="text-[#5A554E] text-sm md:text-base leading-relaxed space-y-5">
            <p className="font-semibold text-[#2C2A26]">THESE TERMS OF USE CONTAIN A MANDATORY ARBITRATION PROVISION THAT, AS SET FORTH IN THE SECTION ENTITLED &ldquo;ARBITRATION&rdquo; BELOW, REQUIRES YOU TO ARBITRATE CLAIMS YOU MAY HAVE AGAINST L&rsquo;OR&Eacute;AL USA S/D, INC. OR ITS AFFILIATES ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES. THIS MEANS YOU CANNOT BRING CLAIMS AGAINST L&rsquo;OR&Eacute;AL USA S/D, INC. OR ITS AFFILIATES IN COURT, AND CONFIRMS YOUR AGREEMENT TO A CLASS ACTION WAIVER IN ARBITRATION. IT AFFECTS YOUR LEGAL RIGHTS. PLEASE READ IT CAREFULLY.</p>

            <h2 className="text-[#2C2A26] text-[18px] md:text-[20px] font-light tracking-[0.06em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>TERMS OF USE</h2>

            <p>Thank you for visiting our site which is owned and operated by L&rsquo;Or&eacute;al USA S/D, Inc. (collectively, &ldquo;We&rdquo;, &ldquo;Us&rdquo;, or &ldquo;Our&rdquo;). Please read these terms of use (&ldquo;Terms of Use&rdquo;) carefully before using the services. THESE TERMS OF USE SET FORTH THE LEGALLY BINDING TERMS OF USE BETWEEN YOU AND US FOR YOUR ACCESS AND USE OF THIS SITE AND ALL OTHER SITES, MOBILE SITES, SERVICES, APPLICATIONS (INCLUDING WEB AND MOBILE), PLATFORMS, AND TOOLS WHERE THESE TERMS OF USE APPEAR OR ARE LINKED (COLLECTIVELY, THE &ldquo;SITE&rdquo;), INCLUDING WITH RESPECT TO ANY RELATED SERVICES, FEATURES, CONTENT, APPS, WIDGETS OFFERED, OR ANY PURCHASES YOU MAKE.</p>

            <p>These Terms of Use apply to all users of the Site, including, without limitation, users who are contributors of content, information and other materials or services on the Site. If you do not agree with the Terms of Use, then you do not have the right to access, view, download or otherwise use the Site or purchase any goods or services and, accordingly, you should not do so. Certain areas, activities, or services within the Site are governed by additional terms and policies. By using those areas, activities, or services, you agree to such additional terms and policies.</p>

            <p>We may at our sole discretion change, add, or delete portions of these Terms of Use at any time on a going-forward basis. It is your responsibility to check these Terms of Use for changes prior to use of the Site, and your continued use of the Site following the posting of changes to these Terms of Use constitutes your acceptance of any changes.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Privacy</h3>
            <p>We have developed a Privacy Policy to inform you of our practices with respect to the collection, use, disclosure, and protection of personal information. You can find the Privacy Policy on our home page. By using this Site you acknowledge you have read and understood Our Privacy Policy.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>General Terms of Use</h3>
            <p>Unless otherwise noted, the products and services on the Site are intended for personal, non-commercial purposes only. You agree to use the Site only for lawful, noncommercial purposes and in compliance with all international, federal, state and local laws. Except as expressly permitted in these Terms of Use, you may not use, reproduce, distribute, reverse engineer, modify, copy, publish, display, transmit, adapt, frame, link, rent, lease, loan, sell, license or in any way exploit the content of the Site. The Site does not provide medical advice, and you should consult with your health care provider for guidance regarding skincare treatments, skin conditions, or any medical concerns.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Eligibility</h3>
            <p>You represent and warrant that you (a) are above the legal age of majority in your jurisdiction of residence, (b) have not previously been suspended or removed from the Site, (c) do not have more than one (1) account at any given time for the Site; (d) you will only provide us with true, accurate, current, and complete information if you register for an account and/or Orders (defined below). If we believe or suspect that your information is not true, accurate, current or complete, or suspect fraudulent use of the site via any automated tools or otherwise, we may deny or terminate your access to the Site or Services (or any portion thereof) and (e) that you have full power and authority to enter into the Terms of Use and in doing so will not violate any other agreement to which you are a party.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Your Account</h3>
            <p>When you create an Account, you are required to provide your name and email address and select a password (collectively, your &ldquo;Account Information&rdquo;), which you must not transfer to or share with any third parties. You must keep all Account Information confidential and not disclose them to any other person or entity. If someone accesses our Site or Services using your Account Information, we will rely on that Account Information and will assume that it is really you or your representative who is accessing the Site and Services. You are solely responsible for all use of your Account Information and all Orders and activities that occur under or in connection with the Account. Without limiting any rights which we may otherwise have, we reserve the right to take all action, as it deems necessary or reasonable, to ensure the security of the Site and your Account, including without limitation, terminating your Account, changing your password, or requesting additional information to authorize transactions on your Account. You agree to be responsible for any act or omission of any users that access the Site or Services under your Account Information that, if undertaken by you, would be deemed a violation of these Terms of Use. You may not use anyone else&rsquo;s Account at any time, without the permission of the Account holder. Please notify us immediately if you become aware that your Account Information is being used without authorization. You agree not to register for more than one Account, register for an Account on behalf of an individual other than yourself without such individual&rsquo;s authorization, or register for an Account on behalf of any group or entity.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>User Content</h3>
            <p>We welcome user comments, information, feedback, and submissions. In addition, you and other users of the Site from time to time may have an opportunity to post on the Site certain ideas, concepts, information, data, text, music, sound, photographs, graphics, video, messages, comments on our products, advertising and other promotional materials or events, facts, advice, &ldquo;tips&rdquo;, opinions and other material (collectively, &ldquo;User Content&rdquo;). Subject to our Privacy Policy, all User Content that you post on this Site will be treated as non-confidential and non-proprietary to you and may be viewed by you and/or other users of this Site. You also agree that we, our affiliates, and our licensees are free to use any ideas, concepts, know-how, or techniques contained in any User Content you send or provide to us for any purpose whatsoever, including, but not limited to, developing, manufacturing and marketing products, services, and content using such information, without any credit, notice, approval or compensation to you. For more information, please see &ldquo;Our Right to Use User Content&rdquo;, below.</p>
            <p>We cannot guarantee that other users will not copy, modify, distribute, or otherwise use the User Content that you share. Therefore, if you have an idea or information that you would like to keep confidential and/or do not want others to use, do not post it on the Site. We and our affiliates are not responsible for any user&rsquo;s misuse or misappropriation of any User Content you post on the Site.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Review of Submissions</h3>
            <p>We have no obligation to verify the identity of any users when they are connected to the Site or to supervise the User Content that has been provided by users. You acknowledge that we may or may not prescreen, monitor, review, edit or delete the User Content posted by you and other users on the Site. We and our designees retain the right to modify, move, refuse, block or remove any User Content, in whole or in part, for any reason or no reason, with or without notice. We and our designees also reserve the right to access, read, preserve, and disclose any information as we reasonably believes is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce these Terms of Use, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect our rights, property or safety, users of the Site and the public.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>User Conduct</h3>
            <p>By posting User Content in or otherwise using any communications service or other interactive service that may be available to you on or through the Site from time to time, you agree that you are the sole responsible person and/or entity from which such User Content originated. Moreover, you agree not to access or use the Site for any purpose that is prohibited by these Terms of Use. You are responsible for all your activity in connection with the Site.</p>
            <p>By way of example, and not as a limitation, you agree not to (and shall not permit any third party to) use the Site to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>upload, post, e-mail, or otherwise transmit any User Content that is inaccurate, unlawful, harmful, threatening, embarrassing, abusive, harassing, tortious, defamatory, vulgar, obscene, offensive, profane, libelous, deceptive, fraudulent, invasive of another&rsquo;s privacy, hateful, or contains or depicts nudity or explicit or graphic descriptions or accounts of sexual or violent acts (including, but not limited to, sexual language of a violent or threatening nature directed at another individual or group of individuals), or is otherwise inappropriate as determined by us in our sole discretion;</li>
              <li>harm any person in any way;</li>
              <li>upload, post, e-mail, or otherwise transmit any User Content that (i) victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of any impermissible classification, including, without limitation, religion, gender, sexual orientation, race, color, creed, ethnicity, national origin, citizenship, age, marital status, veteran status or disability; (ii) infringes any patent, trademark, trade secret, copyright, right of publicity or other intellectual or proprietary right of any party; and (iii) you do not have a right to transmit under any law or under any contractual or fiduciary relationship (such as insider information, intellectual, proprietary or confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
              <li>upload, post, e-mail, or otherwise transmit any material that contains software viruses or any other computer code, files, worms, logic bombs or programs designed or intended to interrupt, disable, damage, destroy, or limit the functionality of the Site or any computer software or hardware or telecommunications equipment or any other similarly destructive activity;</li>
              <li>obtain unauthorized access to any system, data, password or other information;</li>
              <li>interfere with or disrupt the Site or servers or networks linked to the Site, or disobey any requirements, procedures, policies, or regulations of networks linked to the Site;</li>
              <li>intentionally or unintentionally violate any applicable local, state, national, or international law, and any rules, regulations, orders, directives and the like having the force of law, including, without limitation, any laws about exporting data or software to and from the United States or any other country;</li>
              <li>upload, post, e-mail, or otherwise transmit any material, or take any other actions with respect to your use of the Site, that would constitute, or would otherwise encourage, criminal conduct or conduct that could give rise to civil liability;</li>
              <li>for commercial purposes, including, without limitation, submitting any material to solicit funds or to promote, advertise or solicit the sale of any goods or services;</li>
              <li>solicit others to join or become members of any other commercial online service or other online or offline group or organization;</li>
              <li>impersonate any other person or entity, including by providing any false personal information to us (including a false user name) or creating any account for anyone other than yourself;</li>
              <li>submit any person&rsquo;s identification documents or sensitive financial information;</li>
              <li>breach the Privacy Policy;</li>
              <li>to develop or train any artificial intelligence or machine learning algorithms or models;</li>
              <li>to decompile, reverse engineer, disassemble, or otherwise reduce Our Sites to human-readable form, except when these restrictions are prohibited by applicable law;</li>
              <li>harvest, collect, or store information about the users of the Site or the User Content or use such information for any purpose inconsistent with the purpose of the Site or for the purpose of transmitting or facilitating transmission of unsolicited advertising, junk or bulk electronic mail or communications;</li>
              <li>take any action that imposes or may impose (as determined by Us in our sole discretion) an unreasonable or disproportionately large load on our infrastructure;</li>
              <li>interfere or attempt to interfere with the proper working of the Site or any activities conducted on the Site;</li>
              <li>bypass any measures we may use to prevent or restrict access to the Site or portions thereof (or other accounts, computer systems or networks connected to the Site);</li>
              <li>run any form of auto-responder or &ldquo;spam&rdquo; on the Site;</li>
              <li>use manual or automated software, devices, or other processes to &ldquo;crawl&rdquo; or &ldquo;spider&rdquo; any page of the Site;</li>
              <li>harvest or scrape any content from the Site; or</li>
              <li>assist any person in doing any of the above.</li>
            </ul>
            <p>Violation of any of the foregoing or any other provision of these Terms of Use may result in immediate termination of your license to access or use the Site and may subject you to state and federal penalties and other legal consequences. We reserve the right, but shall have no obligation, to investigate your use of the Site to (1) determine whether a violation of the Terms of Use has occurred or (2) comply with any applicable law, regulation, legal process, or governmental request.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>No Endorsement</h3>
            <p>We do not control the User Content posted on the Site and, as such, we make no representations or warranties regarding User Content or its truthfulness, accuracy, reliability, integrity, or quality. We do not determine whether User Content violates the rights of others, and we have no control over whether User Content is of a nature that you or other users may find offensive. User Content includes the opinions, statements, and other content of third parties, not us. You acknowledge and agree that the information and views expressed by you and other users in User Content appearing on the Site do not necessarily reflect our views or those of our content providers, advertiser, sponsors, affiliated or related entities, and we do not support or endorse any User Content or any other content posted by you or any other user on or otherwise accessible through the Site.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Our Right to Use User Content</h3>
            <p>You do not have to submit anything to us, but if you choose to submit any User Content to the Site, it will be deemed non-proprietary and non-confidential and may be used by us, our affiliates or others without restriction. You represent and warrant that you own or otherwise control any and all rights in and to the User Content that you submit and that our public posting and use of that User Content will not infringe or violate the rights of any third party in any manner, including without limitation any privacy rights, publicity rights, copyrights, contract rights or any other intellectual property or proprietary rights. By submitting, sending, posting, uploading, modifying or otherwise providing information, material, or any other communication to us including User Content, whether solicited or unsolicited, you grant us and our designees the royalty-free, fully paid, unrestricted, worldwide, perpetual, irrevocable, non-exclusive, and fully transferable, assignable, sublicensable right and license to use, copy, reproduce, modify, adapt, publish, translate, create derivative works from, improve, distribute, commercialize, perform, or display such User Content (in whole or in part) worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed for any purpose, including, without limitation, advertising and promotional purposes, reproduction, transmission, publication, broadcast and posting without any further consent by you or notice, credit and/or compensation to you or any third parties. You also hereby do and shall grant each user of the Site a non-exclusive license to access your User Content through the Site, and to use, edit, modify, reproduce, distribute, prepare derivative works of, display and perform such User Content. We and our designees also have the right, but not the obligation, to use your user name (and real name, image, likeness or other identifying information, if provided in connection with User Content), city and state in connection with broadcast, print, online or other use or publication of your User Content. We and our designees may use or otherwise transfer, remove or dispose of any and all User Content without restriction and users of the Site shall not be entitled to any compensation whatsoever for any such use, transfer or disposition of User Content by us. Notwithstanding the foregoing, personally identifiable data, if any, included in User Content is handled in accordance with our Privacy Policy.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Transmitting Materials</h3>
            <p>You understand that the technical processing and transmission of the Site may involve (a) transmissions over various networks and (b) changes to conform and adapt to technical requirements of connecting networks or devices. We assume no responsibility for the deletion or failure to store postings or other information submitted by you or other users of the Site.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Product Availability</h3>
            <p>The availability of the products and services described on the Site, and the descriptions of such products and services, may vary based on location and timing.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Auto Refill</h3>
            <p>This site may offer you the opportunity to subscribe to auto-refill your purchase. Your subscription will continue until you cancel it. A recurring charge (in the amount of the product selected for auto replenishment) will be automatically charged to your credit card each time the order ships. The shipment schedule will follow the frequency you requested when you selected the product. There is no minimum term of the subscription and no minimum purchase obligation.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Orders, Prohibition on Reselling</h3>
            <p>While it is our practice to confirm orders by email, the receipt of an email order confirmation does not constitute our acceptance of an order or our confirmation of an offer to sell a product or service. We reserve the right, without prior notice, to limit the order quantity on any product or service and/or to refuse service to any customer. We also may require verification of information prior to the acceptance and/or shipment of any order.</p>
            <p>All orders shipped are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
            <p>You may not purchase any item from this site for resale by you or any other person. The prices displayed on the site are quoted in U.S. dollars and are intended to be valid and effective only in the United States. We have the right to refuse or cancel orders placed, including but not limited to orders where product(s) is listed at an incorrect price regardless of whether the order has been confirmed or your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we will issue a credit to your credit card account.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Intellectual Property Rights</h3>
            <p>The Site, and all of its contents, including but not limited to articles, other text, photographs, images, illustrations, graphics, video material, audio material, including musical compositions and sound recordings, software, logos, titles, characters, names, graphics and button icons, excluding User Content (collectively &ldquo;Proprietary Material&rdquo;), are protected by copyright, trademark and other laws of the United States, as well as international conventions and the laws of other countries. The Proprietary Material is owned or controlled by L&rsquo;Or&eacute;al or by other parties that have provided rights thereto to L&rsquo;Or&eacute;al.</p>
            <p>Except as otherwise provided in these Terms of Use or without our express prior written permission, you may not, and agree that you will not, use, publish, reproduce, display, publicly perform, create derivative works from, reverse engineer or decompile, disassemble, distribute, license, transfer, sell, copy, post, enter into a database, upload, transmit or modify the Proprietary Material or any portion thereof, for any purpose or by any means, method, or process now known or later developed. Modification of the materials appearing on the Site or use of such materials for any other purpose is a violation of our copyright and other proprietary rights.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Claims Regarding Copyright Infringement</h3>
            <p>L&rsquo;Or&eacute;al respects the intellectual property rights of others. If you are a copyright owner or an agent thereof and believe that any User Content or other content on the Site infringes your copyright, you may submit a notification pursuant to the Digital Millennium Copyright Act (&ldquo;DMCA&rdquo;) by providing our Copyright Agent with the following information in writing (see 17 U.S.C &sect; 512(c)(3) for further detail):</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>A physical or electronic signature of the owner or a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
              <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;</li>
              <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit us to locate the material;</li>
              <li>Information reasonably sufficient to permit us to contact you, such as your name, address, telephone number, and, if available, your email address;</li>
              <li>A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
              <li>A statement, under penalty of perjury, that the information in the above notification is accurate and that you are, or are authorized to act on behalf of, the owner of an exclusive right that is allegedly infringed.</li>
            </ul>
            <p>If you fail to comply with all of the requirements set forth above, your DMCA notification may not be effective. Our designated Copyright Agent to receive notifications of claimed infringement is:</p>
            <p className="pl-6">DMCA Agent c/o L&rsquo;Or&eacute;al USA Legal Department<br />10 Hudson Yards<br />501 West 30 Street<br />New York, NY 10001<br />DMCA@loreal.com</p>
            <p>After receiving an effective notification of claimed infringement, we will process and investigate the claim and, if appropriate, will act expeditiously to remove or disable access to material claimed to be infringing. We also will take reasonable steps promptly to notify the uploading user that the material has been removed or disabled at your request.</p>
            <p>This notification process does not limit L&rsquo;Or&eacute;al&rsquo;s ability to exercise any other rights or pursue any other remedies it may have to address claims of infringement.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Account Termination</h3>
            <p>We may, in appropriate circumstances, terminate your account for the Site and any or all affiliate websites if you are a repeat infringer. If you believe that a user is a repeat infringer, please follow the instructions above to contact our Copyright Agent and provide information sufficient for us to verify that the user is a repeat infringer.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Third Party Websites and Links</h3>
            <p>You may be able to link to third party Websites, services or resources on the Internet from the Site, and third-party Websites, services or resources may contain links to the Site (collectively, &ldquo;Linked Sites&rdquo;). We are not responsible for the content, availability, advertising, products, services or other materials of any such Linked Sites, or any additional links contained therein, and our inclusion of links to the Linked Sites on the Sites does not imply that we endorse or approve of any materials contained on, or accessible through, the Linked Sites. In no event shall we be liable, directly or indirectly, to you or any other person or entity for any loss or damage arising from or occasioned by the creation or use of the Linked Sites or the information or material accessed through these Linked Sites.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Third Party Merchants</h3>
            <p>The Site may enable you to order and receive products, information and services from businesses that are not owned or operated by us. The purchase, payment, warranty, guarantee, delivery, maintenance, and all other matters concerning the merchandise, services or information, opinion or advice ordered or received from such businesses are solely between you and such businesses. We do not endorse, warrant, or guarantee such products, information, or services. We will not be a party to or in any way responsible for monitoring any transaction between you and third-party providers of such products, services, or information, or for ensuring the confidentiality of your transactions.</p>
            <p>We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Advertisements, Sponsorships, Co-Promotions and Other Partnerships</h3>
            <p>We may display advertisements for the goods and services of a third party on the Site, including in connection with co-promotions, sponsorships and other similar partnership arrangements. We do not endorse or represent and are not responsible for the safety, quality, accuracy, reliability, integrity or legality of any such advertised goods or services.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Contests, Sweepstakes, and Other Promotions</h3>
            <p>This Site may, from time to time, contain contests, sweepstakes, or other promotions that offer prizes or that require you to submit material or information about yourself. Each has its own rules, which you must read and agree to before you may enter.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Events</h3>
            <p>You may be invited or asked to attend events we sponsor, or events held by other members and users of the Site which are not in any way associated with us (collectively, &ldquo;Events&rdquo;). Your participation in any Events is at your own risk.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>1-on-1 Video Consultation Services</h3>
            <p>This site may allow you to use a video consultation feature either with automated tools, a live consultation with a beauty advisor, or both. By using the service, you agree to allow to activate your camera to connect automated tools, live consultation with a beauty advisor, or both. A video consultation is a live experience and will not be recorded.</p>
            <p>When participating in a live consultation with a beauty advisor, the beauty advisor can answer your questions, recommend products, and, where available, allow you to virtually try products during the live consultation. You will be able to see the recommend products during the experience, and you can shop and buy products after the video consultation has ended. To help us in providing you with the best experience and advice, the beauty advisor is informed about the page you were consulting when you connected to this service.</p>
            <p>By using video consultation features, you agree to be bound by these Terms of Use and comply with its provisions, including provisions related to User Conduct.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Artificial Intelligence &mdash; Acceptable Use</h3>
            <p>Our Site may allow you to submit text, documents, or other materials to the Site for processing (referred to herein as &ldquo;Prompts&rdquo;), and Our Site may, using artificial intelligence (such as machine learning, deep learning, computer vision, or generative AI), generate responses based on your Prompts (referred to herein as &ldquo;Outputs&rdquo;). Prompts and Outputs are considered User Content for purposes of these Terms of Use. By submitting Prompts, you agree (A) you have all rights, and have provided any notices and obtained any consents, that are necessary for Us to process any Prompts you submit to the Sites in accordance with Our Terms of Use; and (B) your submission of Prompts will not violate Our Terms of Use or any laws applicable to those Prompts.</p>
            <p>The foregoing functionality is intended for informational and recreational purposes only. It is not a medical device and does not replace diagnostic and professional advice from health care professionals, including dermatologists. Our Site does not provide medical advice. We recommend consulting a health care professional for specific concerns or conditions.</p>
            <p>Your interactions with this functionality are not monitored by a human being. It is your responsibility to exercise discretion and judgment when following any recommendations or advice provided by Our Sites. We recommend you review product ingredients and instructions on product packaging and product inserts before use. There may be instances where the Outputs are not entirely accurate, complete, or may not meet your expectations.</p>
            <p>In addition to other provisions of the Terms of Use, you shall not use the Site to generate Outputs for the purpose of:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>compromising security or gaining unauthorized access to computer system or networks, including spoofing and social engineering;</li>
              <li>diverting our Site from its intended purpose(s), including to generate Outputs that are prohibited by these Terms of Use or using the Site in a way that is likely to generate undesired content due to limitations in the models;</li>
              <li>generating content for fraudulent activities, scams, phishing, or malware;</li>
              <li>generating content that describes, features, or promotes, or is used for, purposes of commercial sexual activity and sexual services;</li>
              <li>generating or promoting disinformation, misinformation, or false online engagement;</li>
              <li>inciting violence, racial, or ethnic hatred;</li>
              <li>inciting or encouraging crimes or offenses, or otherwise in connection with illegal activities, including, without limitation, human trafficking or any use that exploits or abuses minors;</li>
              <li>interfering or negatively impacting Our products and services;</li>
              <li>impersonating another individual or organization;</li>
              <li>politics, propaganda, or proselytizing;</li>
              <li>promoting or facilitating the generation or distribution of spam;</li>
              <li>violating a third party&rsquo;s rights;</li>
              <li>using Prompts and Outputs to train or improve models (e.g., model scraping); and</li>
              <li>any combination of the foregoing.</li>
            </ul>
            <p>In addition to the other provisions of the Terms of Use, you agree to not submit Prompts that:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>are harmful, defamatory, malicious, infringes on privacy or publicity rights, or qualifies as gross indecency;</li>
              <li>include sensitive personal information, such as: Financial account information (e.g., bank account information, payment information (e.g., credit or debit card numbers, bank account information)); Government identifiers; Health conditions or diagnoses; or Security information (e.g., API keys or passwords);</li>
              <li>include confidential or proprietary information that you are not authorized to disclose;</li>
              <li>include information that is racist, violent, xenophobic, malicious, rude, obscene, or unlawful;</li>
              <li>may directly or indirectly allow the nominal and specific identification of an individual without prior and express consent, such as an individual&rsquo;s last name, postal address, email address, telephone number, or any combination of the foregoing;</li>
              <li>include information (including photographs) portraying or relating to minors, including content related to grooming, pedophilia, nudity, or that describes, encourages, or supports, abuse of minors; or</li>
              <li>include information involving nudity, non-consensual intimate content, pornography, offensive language, violence, or illegal activity.</li>
            </ul>
            <p>You shall not capture, record, and/or disseminate conversational screens that are part of Our Site.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Use of Software</h3>
            <p>We may make software available for you to download or use. Such software will be subject to the terms of the license agreement that accompanies it. If there is no license agreement presented to you with the software, then the following license, in addition to the other terms of these Terms of Use govern your use of such software. We grant you a personal, non-exclusive, non-transferable, limited license to install the software on any single computer. The software is protected by copyright and other intellectual property laws and treaties and is owned by us or our suppliers. You may not: (i) copy, sell, redistribute, rent, lease or otherwise transfer the software or any of the limited rights you receive hereunder; (ii) incorporate it or any portion of it into another product; (iii) reverse engineer, decipher, decompile, or disassemble the software or otherwise attempt to derive the source code or underlying ideas or algorithms of the software or any portion of the software, including without limitation any application or widget (except where expressly permitted by law); (iv) export, re-export, transfer and/or release the software, related technology, or any product thereof, for any proscribed end-use, or to any proscribed country, entity or person (wherever located), without proper authorization from the U.S. and/or foreign government; (v) modify, translate, adapt, or create derivative works from the software or any portion of the software in any way or remove proprietary notices in the software. You agree to abide by all laws and regulations in effect regarding your use of the software. You may not authorize or assist any third party to do any of the things prohibited in this paragraph.</p>
            <p>We may automatically check your version of the software and update it to improve its performance and capabilities. If you shut down the software during an automatic update or otherwise interfere with the installation of the update, the software may be damaged and/or cease to operate.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Termination</h3>
            <p>We may terminate or suspend your access to the Site, delete your profile and any content or information that you have posted on the Site, and/or prohibit you from using or accessing the Site (or any portion, aspect, or feature of the Site) for any reason, or no reason, at any time in our sole discretion, with or without notice to you, effective immediately, which may result in the forfeiture and destruction of all information associated with you and your activities in connection with the Site. If you wish to terminate your account, you may do so by following the instructions on the Site, however, please note that any loyalty rewards or benefits associated with your account may be forfeited as a result of such account termination. Any fees paid hereunder are non-refundable. In the event of termination, you will still be bound by your obligations under these Terms of Use.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Governing Law; General Information</h3>
            <p>We control and operate the Site from our offices in the State of New York, United States of America. While we invite visitors from all parts of the world to visit the Site, visitors acknowledge that the Site, and all activities available on and through the Site, are governed by the laws of the United States of America and the laws of the State of New York. We do not represent that materials on the Site are appropriate or available for use in other locations. Persons who choose to access the Site from other locations do so on their own initiative and are responsible for compliance with local laws.</p>
            <p>You agree that the laws of the State of New York, excluding its conflict of laws rules, and these Terms of Use, and any other policies posted from time to time on the Site applicable to your use of the Site shall govern your use of the Site. Please note that your use of the Site may be subject to other local, state, national, and international laws. You expressly agree that exclusive jurisdiction for any claim or dispute with us (or any of our affiliates) or relating in any way to your use of the Site resides in the courts of the County of New York, State of New York, and you further agree and expressly consent to the exercise of personal jurisdiction in the courts of the County of New York, State of New York, in connection with any such dispute and including any claim involving us or our affiliates, subsidiaries, employees, contractors, officers, directors, telecommunication providers and content providers.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Arbitration</h3>
            <p>By using this Site, you agree that L&rsquo;Or&eacute;al USA or one of its affiliates at its sole discretion, may require that: (1) any and all disputes and causes of action related to or connected with these Terms, the Site, and the related offerings shall be resolved individually, without resort to any form of class action, and exclusively by final and binding arbitration under the rules of the American Arbitration Association and held at the AAA regional office nearest the participant; (2) the Federal Arbitration Act shall govern the interpretation, enforcement and all proceedings at such arbitration; and (3) judgment upon such arbitration award may be entered in any court having jurisdiction. You understand and agree that you are waiving your right to sue or go to court to assert or defend your rights under this contract.</p>
            <p>A printed version of the Terms of Use and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to the Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
            <p>These Terms of Use are the entire agreement between you and us with respect to the Site and any User Content and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and us with respect to those matters. If any provision of these Terms of Use is found to be illegal or unenforceable, the remainder of the Terms of Use shall be unaffected and shall continue to be fully valid, binding, and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. No agency, partnership, joint venture, or employment relationship is created as a result of these Terms of Use, and neither party has any authority of any kind to bind the other in any respect.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>No Waiver</h3>
            <p>No failure on the part of L&rsquo;Or&eacute;al USA to enforce any part of the Terms shall constitute a waiver of any of L&rsquo;Or&eacute;al USA&rsquo;s rights under the Terms whether for part or future actions on the part of any person. Neither the receipt of any funds by L&rsquo;Or&eacute;al USA nor the reliance of any person on L&rsquo;Or&eacute;al USA&rsquo;s actions shall be deemed to constitute a waiver of any part of the Terms. Only a specific, written waiver signed by an authorized representative of L&rsquo;Or&eacute;al USA shall have any legal effect whatsoever.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Limitation of Liability; Disclaimer of Warranties</h3>
            <p>YOUR USE OF THE SITE IS SOLELY AT YOUR OWN RISK. THE SITE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS AND, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE AND OUR PROVIDERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, IMPLIED WARRANTIES OF MERCHANTABILITY, ACCURACY, AVAILABILITY, RELIABILITY, SECURITY, PRIVACY, COMPATIBILITY, NON-INFRINGEMENT, AND ANY WARRANTY IMPLIED BY COURSE OF DEALING, COURSE OF PERFORMANCE, OR TRADE USAGE.</p>
            <p>TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, IN NO EVENT WILL WE, OUR PROVIDERS, OR OUR OR THEIR RESPECTIVE AFFILIATES, INVESTORS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SUCCESSORS OR ASSIGNS (COLLECTIVELY, THE &ldquo;L&rsquo;OREAL PARTIES&rdquo;), BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR OTHER DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO THE SITE OR THESE TERMS (INCLUDING ARISING OUT OF OR IN CONNECTION WITH YOUR USE OR INABILITY TO USE THE SITE), WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHER THEORY, EVEN IF ANY L&rsquo;OREAL PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES, AND EVEN IF THE DAMAGES ARE FORESEEABLE.</p>
            <p>TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, THE L&rsquo;OREAL PARTIES&rsquo; TOTAL AGGREGATE LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION ARISING OUT OF OR IN ANY WAY RELATED TO THE SITE OR THESE TERMS, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WILL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID TO US FOR ACCESS TO OR USE OF THE SITE (IF ANY) IN THE SIX MONTHS PRECEDING THE DATE SUCH DAMAGES, LOSSES, AND CAUSES OF ACTION FIRST AROSE, OR $1,000. THE FOREGOING LIMITATIONS ARE ESSENTIAL TO THESE TERMS, AND WE WOULD NOT OFFER THE SERVICES TO YOU UNDER THESE TERMS WITHOUT THESE LIMITATIONS.</p>
            <p>YOU AGREE TO INDEMNIFY AND HOLD HARMLESS THE L&rsquo;OREAL PARTIES FROM AND AGAINST ANY AND ALL LIABILITIES, CLAIMS, DAMAGES, EXPENSES (INCLUDING REASONABLE ATTORNEYS&rsquo; FEES AND COSTS), AND OTHER LOSSES ARISING OUT OF OR RELATED TO YOUR BREACH OR ALLEGED BREACH OF THESE TERMS; YOUR ACCESS TO, USE OF, OR ALLEGED USE OF THE SITE; YOUR FEEDBACK; YOUR VIOLATION OF APPLICABLE LAW OR ANY THIRDPARTY RIGHT; AND ANY ACTUAL OR ALLEGED FRAUD, INTENTIONAL MISCONDUCT, GROSS NEGLIGENCE, OR CRIMINAL ACTS COMMITTED BY YOU OR YOUR AGENTS. WE RESERVE THE RIGHT TO ENGAGE SEPARATE COUNSEL AND PARTICIPATE IN OR ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU HEREUNDER, IN WHICH CASE YOU AGREE TO COOPERATE WITH US AND SUCH SEPARATE COUNSEL AS WE REASONABLY REQUEST.</p>
            <p>THE LAWS OF SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES OR CERTAIN TYPES OF DAMAGES, SO SOME OR ALL OF THE DISCLAIMERS AND LIMITATIONS OF LIABILITY IN THESE TERMS MAY NOT APPLY TO YOU.</p>
            <p>Any cause of action or claim you may have directly or indirectly arising out of or relating to the Terms of Use or the Site (including the purchase of products via the Site) must be commenced within one (1) year after the claim or cause of action arises.</p>
            <p>The Privacy Policy provides separate options for individuals to lodge complaints in relation to the Privacy Policy and personal information.</p>

            <h3 className="text-[#2C2A26] text-[16px] md:text-[17px] font-light tracking-[0.04em] pt-6" style={{ fontFamily: "var(--font-serif)" }}>Notices</h3>
            <p>Unless otherwise specified in these Terms of Use, all notices under these Terms of Use will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or email; or the day after it is sent, if sent for next day delivery by recognized overnight delivery service.</p>
            <p>Please feel free to contact us via one of the methods described on our Contact Us page. You agree that we may send notices to you regarding your use of the Site by means of electronic mail, a general notice posted on the Site or by written communication delivered either by overnight courier or U.S. mail to your email or mailing address as appearing in our records from time to time.</p>
            <p>These Terms of Use were last updated January 2026.</p>
          </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
